# MongoDB connection URL
mongo-url = "mongodb://root:rootpassword@localhost:27017/admin?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.3"

# Elasticsearch connection URLs (plural, as an array)
elasticsearch-urls = ["http://elasticsearch:9200"]

# Namespace regex for filtering the MongoDB collections to sync
namespace-regex = "amazon_scrapping.*"

# Specify the namespaces (databases and collections) to track with change streams
change-stream-namespaces = [
  "amazon_scrapping.product_scrapping_theme",
  "amazon_scrapping.product_scrapping_url",
  "amazon_scrapping.scrapping_tasks"
]

direct-read-namespaces = [
  "amazon_scrapping.product_scrapping_theme",
  "amazon_scrapping.product_scrapping_url",
  "amazon_scrapping.scrapping_tasks"
]


# Enable gzip compression for Elasticsearch requests
gzip = true
